package com.worthytrip.shopping.dao.model.flightdata;

import com.alibaba.fastjson.JSON;
import com.google.common.base.Objects;

public class FixedFlight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.id
     *
     * @mbggenerated
     */
    private Integer id;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FixedFlight that = (FixedFlight) o;
        return Objects.equal(fromcity, that.fromcity) &&
                Objects.equal(tocity, that.tocity) &&
                Objects.equal(startdate, that.startdate) &&
                Objects.equal(retdate, that.retdate) &&
                Objects.equal(adultnumber, that.adultnumber) &&
                Objects.equal(childnumber, that.childnumber) &&
                Objects.equal(flightoption, that.flightoption) &&
                Objects.equal(ipcc, that.ipcc);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode( fromcity, tocity, startdate, retdate, adultnumber, childnumber, flightoption, ipcc);
    }

    @Override
    public String toString() {
        return JSON.toJSONString(this);
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.fromCity
     *
     * @mbggenerated
     */
    private String fromcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.toCity
     *
     * @mbggenerated
     */
    private String tocity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.startDate
     *
     * @mbggenerated
     */
    private Integer startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.retDate
     *
     * @mbggenerated
     */
    private Integer retdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.adultNumber
     *
     * @mbggenerated
     */
    private Integer adultnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.childNumber
     *
     * @mbggenerated
     */
    private Integer childnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.flightOption
     *
     * @mbggenerated
     */
    private Integer flightoption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_flight.ipcc
     *
     * @mbggenerated
     */
    private String ipcc;

    private String grabSwitch;

    public String getGrabSwitch() {
        return grabSwitch;
    }

    public void setGrabSwitch(String grabSwitch) {
        this.grabSwitch = grabSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.id
     *
     * @return the value of fixed_flight.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.id
     *
     * @param id the value for fixed_flight.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.fromCity
     *
     * @return the value of fixed_flight.fromCity
     * @mbggenerated
     */
    public String getFromcity() {
        return fromcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.fromCity
     *
     * @param fromcity the value for fixed_flight.fromCity
     * @mbggenerated
     */
    public void setFromcity(String fromcity) {
        this.fromcity = fromcity == null ? null : fromcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.toCity
     *
     * @return the value of fixed_flight.toCity
     * @mbggenerated
     */
    public String getTocity() {
        return tocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.toCity
     *
     * @param tocity the value for fixed_flight.toCity
     * @mbggenerated
     */
    public void setTocity(String tocity) {
        this.tocity = tocity == null ? null : tocity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.startDate
     *
     * @return the value of fixed_flight.startDate
     * @mbggenerated
     */
    public Integer getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.startDate
     *
     * @param startdate the value for fixed_flight.startDate
     * @mbggenerated
     */
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.retDate
     *
     * @return the value of fixed_flight.retDate
     * @mbggenerated
     */
    public Integer getRetdate() {
        return retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.retDate
     *
     * @param retdate the value for fixed_flight.retDate
     * @mbggenerated
     */
    public void setRetdate(Integer retdate) {
        this.retdate = retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.adultNumber
     *
     * @return the value of fixed_flight.adultNumber
     * @mbggenerated
     */
    public Integer getAdultnumber() {
        return adultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.adultNumber
     *
     * @param adultnumber the value for fixed_flight.adultNumber
     * @mbggenerated
     */
    public void setAdultnumber(Integer adultnumber) {
        this.adultnumber = adultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.childNumber
     *
     * @return the value of fixed_flight.childNumber
     * @mbggenerated
     */
    public Integer getChildnumber() {
        return childnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.childNumber
     *
     * @param childnumber the value for fixed_flight.childNumber
     * @mbggenerated
     */
    public void setChildnumber(Integer childnumber) {
        this.childnumber = childnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.flightOption
     *
     * @return the value of fixed_flight.flightOption
     * @mbggenerated
     */
    public Integer getFlightoption() {
        return flightoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.flightOption
     *
     * @param flightoption the value for fixed_flight.flightOption
     * @mbggenerated
     */
    public void setFlightoption(Integer flightoption) {
        this.flightoption = flightoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_flight.ipcc
     *
     * @return the value of fixed_flight.ipcc
     * @mbggenerated
     */
    public String getIpcc() {
        return ipcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_flight.ipcc
     *
     * @param ipcc the value for fixed_flight.ipcc
     * @mbggenerated
     */
    public void setIpcc(String ipcc) {
        this.ipcc = ipcc == null ? null : ipcc.trim();
    }
}