package com.worthytrip.shopping.dao.model.flightdata;

import com.alibaba.fastjson.JSON;

public class OrderPnr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.sessionId
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.pnrCode
     *
     * @mbggenerated
     */
    private String pnrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.adultNumber
     *
     * @mbggenerated
     */
    private Integer adultnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.childNumber
     *
     * @mbggenerated
     */
    private Integer childnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pnr.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    private String fromCity;

    private String toCity;

    private String ipcc;

    public String getFromCity() {
        return fromCity;
    }

    public void setFromCity(String fromCity) {
        this.fromCity = fromCity;
    }

    public String getToCity() {
        return toCity;
    }

    public void setToCity(String toCity) {
        this.toCity = toCity;
    }

    public String getIpcc() {
        return ipcc;
    }

    public void setIpcc(String ipcc) {
        this.ipcc = ipcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.id
     *
     * @return the value of order_pnr.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.id
     *
     * @param id the value for order_pnr.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.sessionId
     *
     * @return the value of order_pnr.sessionId
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.sessionId
     *
     * @param sessionid the value for order_pnr.sessionId
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.pnrCode
     *
     * @return the value of order_pnr.pnrCode
     *
     * @mbggenerated
     */
    public String getPnrcode() {
        return pnrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.pnrCode
     *
     * @param pnrcode the value for order_pnr.pnrCode
     *
     * @mbggenerated
     */
    public void setPnrcode(String pnrcode) {
        this.pnrcode = pnrcode == null ? null : pnrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.adultNumber
     *
     * @return the value of order_pnr.adultNumber
     *
     * @mbggenerated
     */
    public Integer getAdultnumber() {
        return adultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.adultNumber
     *
     * @param adultnumber the value for order_pnr.adultNumber
     *
     * @mbggenerated
     */
    public void setAdultnumber(Integer adultnumber) {
        this.adultnumber = adultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.childNumber
     *
     * @return the value of order_pnr.childNumber
     *
     * @mbggenerated
     */
    public Integer getChildnumber() {
        return childnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.childNumber
     *
     * @param childnumber the value for order_pnr.childNumber
     *
     * @mbggenerated
     */
    public void setChildnumber(Integer childnumber) {
        this.childnumber = childnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pnr.createTime
     *
     * @return the value of order_pnr.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pnr.createTime
     *
     * @param createtime the value for order_pnr.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    @Override
    public String toString() {
        return JSON.toJSONString(this);
    }
}