package com.worthytrip.shopping.dao.model.codedata;

public class CityCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.airportCode
     *
     * @mbggenerated
     */
    private String airportcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.airportNameEN
     *
     * @mbggenerated
     */
    private String airportnameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.airportNameCH
     *
     * @mbggenerated
     */
    private String airportnamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.cityCode
     *
     * @mbggenerated
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.cityNameEN
     *
     * @mbggenerated
     */
    private String citynameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.cityNameCH
     *
     * @mbggenerated
     */
    private String citynamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.countryNameEN
     *
     * @mbggenerated
     */
    private String countrynameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.countryNameCH
     *
     * @mbggenerated
     */
    private String countrynamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.areaNameEN
     *
     * @mbggenerated
     */
    private String areanameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.areaNameCH
     *
     * @mbggenerated
     */
    private String areanamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.continentNameEN
     *
     * @mbggenerated
     */
    private String continentnameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.continentNameCH
     *
     * @mbggenerated
     */
    private String continentnamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.globalCode
     *
     * @mbggenerated
     */
    private String globalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.countryAreaEN
     *
     * @mbggenerated
     */
    private String countryareaen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_code.countryAreaCH
     *
     * @mbggenerated
     */
    private String countryareach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.id
     *
     * @return the value of city_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.id
     *
     * @param id the value for city_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.airportCode
     *
     * @return the value of city_code.airportCode
     *
     * @mbggenerated
     */
    public String getAirportcode() {
        return airportcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.airportCode
     *
     * @param airportcode the value for city_code.airportCode
     *
     * @mbggenerated
     */
    public void setAirportcode(String airportcode) {
        this.airportcode = airportcode == null ? null : airportcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.airportNameEN
     *
     * @return the value of city_code.airportNameEN
     *
     * @mbggenerated
     */
    public String getAirportnameen() {
        return airportnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.airportNameEN
     *
     * @param airportnameen the value for city_code.airportNameEN
     *
     * @mbggenerated
     */
    public void setAirportnameen(String airportnameen) {
        this.airportnameen = airportnameen == null ? null : airportnameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.airportNameCH
     *
     * @return the value of city_code.airportNameCH
     *
     * @mbggenerated
     */
    public String getAirportnamech() {
        return airportnamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.airportNameCH
     *
     * @param airportnamech the value for city_code.airportNameCH
     *
     * @mbggenerated
     */
    public void setAirportnamech(String airportnamech) {
        this.airportnamech = airportnamech == null ? null : airportnamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.cityCode
     *
     * @return the value of city_code.cityCode
     *
     * @mbggenerated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.cityCode
     *
     * @param citycode the value for city_code.cityCode
     *
     * @mbggenerated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.cityNameEN
     *
     * @return the value of city_code.cityNameEN
     *
     * @mbggenerated
     */
    public String getCitynameen() {
        return citynameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.cityNameEN
     *
     * @param citynameen the value for city_code.cityNameEN
     *
     * @mbggenerated
     */
    public void setCitynameen(String citynameen) {
        this.citynameen = citynameen == null ? null : citynameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.cityNameCH
     *
     * @return the value of city_code.cityNameCH
     *
     * @mbggenerated
     */
    public String getCitynamech() {
        return citynamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.cityNameCH
     *
     * @param citynamech the value for city_code.cityNameCH
     *
     * @mbggenerated
     */
    public void setCitynamech(String citynamech) {
        this.citynamech = citynamech == null ? null : citynamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.countryNameEN
     *
     * @return the value of city_code.countryNameEN
     *
     * @mbggenerated
     */
    public String getCountrynameen() {
        return countrynameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.countryNameEN
     *
     * @param countrynameen the value for city_code.countryNameEN
     *
     * @mbggenerated
     */
    public void setCountrynameen(String countrynameen) {
        this.countrynameen = countrynameen == null ? null : countrynameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.countryNameCH
     *
     * @return the value of city_code.countryNameCH
     *
     * @mbggenerated
     */
    public String getCountrynamech() {
        return countrynamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.countryNameCH
     *
     * @param countrynamech the value for city_code.countryNameCH
     *
     * @mbggenerated
     */
    public void setCountrynamech(String countrynamech) {
        this.countrynamech = countrynamech == null ? null : countrynamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.areaNameEN
     *
     * @return the value of city_code.areaNameEN
     *
     * @mbggenerated
     */
    public String getAreanameen() {
        return areanameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.areaNameEN
     *
     * @param areanameen the value for city_code.areaNameEN
     *
     * @mbggenerated
     */
    public void setAreanameen(String areanameen) {
        this.areanameen = areanameen == null ? null : areanameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.areaNameCH
     *
     * @return the value of city_code.areaNameCH
     *
     * @mbggenerated
     */
    public String getAreanamech() {
        return areanamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.areaNameCH
     *
     * @param areanamech the value for city_code.areaNameCH
     *
     * @mbggenerated
     */
    public void setAreanamech(String areanamech) {
        this.areanamech = areanamech == null ? null : areanamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.continentNameEN
     *
     * @return the value of city_code.continentNameEN
     *
     * @mbggenerated
     */
    public String getContinentnameen() {
        return continentnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.continentNameEN
     *
     * @param continentnameen the value for city_code.continentNameEN
     *
     * @mbggenerated
     */
    public void setContinentnameen(String continentnameen) {
        this.continentnameen = continentnameen == null ? null : continentnameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.continentNameCH
     *
     * @return the value of city_code.continentNameCH
     *
     * @mbggenerated
     */
    public String getContinentnamech() {
        return continentnamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.continentNameCH
     *
     * @param continentnamech the value for city_code.continentNameCH
     *
     * @mbggenerated
     */
    public void setContinentnamech(String continentnamech) {
        this.continentnamech = continentnamech == null ? null : continentnamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.globalCode
     *
     * @return the value of city_code.globalCode
     *
     * @mbggenerated
     */
    public String getGlobalcode() {
        return globalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.globalCode
     *
     * @param globalcode the value for city_code.globalCode
     *
     * @mbggenerated
     */
    public void setGlobalcode(String globalcode) {
        this.globalcode = globalcode == null ? null : globalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.countryAreaEN
     *
     * @return the value of city_code.countryAreaEN
     *
     * @mbggenerated
     */
    public String getCountryareaen() {
        return countryareaen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.countryAreaEN
     *
     * @param countryareaen the value for city_code.countryAreaEN
     *
     * @mbggenerated
     */
    public void setCountryareaen(String countryareaen) {
        this.countryareaen = countryareaen == null ? null : countryareaen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_code.countryAreaCH
     *
     * @return the value of city_code.countryAreaCH
     *
     * @mbggenerated
     */
    public String getCountryareach() {
        return countryareach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_code.countryAreaCH
     *
     * @param countryareach the value for city_code.countryAreaCH
     *
     * @mbggenerated
     */
    public void setCountryareach(String countryareach) {
        this.countryareach = countryareach == null ? null : countryareach.trim();
    }
}